package at.ac.ait

object Fields {
  val height = "height"
  val timestamp = "timestamp"
  val date = "date"
  val txHash = "txHash"
  val txIndex = "txIndex"
  val txPrefix = "txPrefix"
  val value = "value"
  val addresses = "addresses"
  val address = "address"
  val addressPrefix = "addressPrefix"
  val totalInput = "totalInput"
  val totalOutput = "totalOutput"
  val n = "n"
  val noIncomingTxs = "noIncomingTxs"
  val noOutgoingTxs = "noOutgoingTxs"
  val firstTx = "firstTx"
  val lastTx = "lastTx"
  val totalReceived = "totalReceived"
  val totalSpent = "totalSpent"
  val noAddresses = "noAddresses"
  val currency = "currency"
  val eur = "eur"
  val usd = "usd"
  val addressId = "addressId"
  val addressIdGroup = "addressIdGroup"
  val coinjoin = "coinJoin"
  val cluster = "cluster"
  val clusterGroup = "clusterGroup"
  val srcAddressId = "srcAddressId"
  val dstAddressId = "dstAddressId"
  val srcAddressIdGroup = "srcAddressIdGroup"
  val dstAddressIdGroup = "dstAddressIdGroup"
  val srcAddressPrefix = "srcAddressPrefix"
  val dstAddressPrefix = "dstAddressPrefix"
  val srcCluster = "srcCluster"
  val dstCluster = "dstCluster"
  val srcClusterGroup = "srcClusterGroup"
  val dstClusterGroup = "dstClusterGroup"
  val noTransactions = "noTransactions"
  val estimatedValue = "estimatedValue"
  val category = "category"
  val abuse = "abuse"
  val srcProperties = "srcProperties"
  val dstProperties = "dstProperties"
}
