package at.ac.ait

object Fields {
  val height = "height"
  val timestamp = "timestamp"
  val txHash = "txHash"
  val txNumber = "txNumber"
  val txPrefix = "txPrefix"
  val value = "value"
  val addresses = "addresses"
  val address = "address"
  val addressPrefix = "addressPrefix"
  val totalInput = "totalInput"
  val totalOutput = "totalOutput"
  val vin = "vin"
  val vout = "vout"
  val n = "n"
  val txs = "txs"
  val inputs = "inputs"
  val outputs = "outputs"
  val noIncomingTxs = "noIncomingTxs"
  val noOutgoingTxs = "noOutgoingTxs"
  val firstTx = "firstTx"
  val lastTx = "lastTx"
  val totalReceived = "totalReceived"
  val totalSpent = "totalSpent"
  val noAddresses = "noAddresses"
  val eur = "eur"
  val usd = "usd"
  val txId = "txId"
  val addrId = "addrId"
  val cluster = "cluster"
  val srcAddress = "srcAddress"
  val dstAddress = "dstAddress"
  val srcAddressPrefix = "srcAddressPrefix"
  val dstAddressPrefix = "dstAddressPrefix"
  val srcCluster = "srcCluster"
  val dstCluster = "dstCluster"
  val noTransactions = "noTransactions"
  val estimatedValue = "estimatedValue"
  val category = "category"
  val srcCategory = "srcCategory"
  val dstCategory = "dstCategory"
  val srcProperties = "srcProperties"
  val dstProperties = "dstProperties"
}
