package info.graphsense

object Fields {
  val blockId = "blockId"
  val timestamp = "timestamp"
  val date = "date"
  val txHash = "txHash"
  val txId = "txId"
  val txPrefix = "txPrefix"
  val txList = "txList"
  val value = "value"
  val addresses = "addresses"
  val address = "address"
  val addressPrefix = "addressPrefix"
  val totalInput = "totalInput"
  val totalOutput = "totalOutput"
  val n = "n"
  val noIncomingTxs = "noIncomingTxs"
  val noOutgoingTxs = "noOutgoingTxs"
  val isOutgoing = "isOutgoing"
  val firstTxId = "firstTxId"
  val lastTxId = "lastTxId"
  val totalReceived = "totalReceived"
  val totalSpent = "totalSpent"
  val noAddresses = "noAddresses"
  val currency = "currency"
  val active = "active"
  val coinjoin = "coinJoin"
  val addressId = "addressId"
  val addressIdGroup = "addressIdGroup"
  val srcAddressId = "srcAddressId"
  val srcAddressIdGroup = "srcAddressIdGroup"
  val dstAddressId = "dstAddressId"
  val dstAddressIdGroup = "dstAddressIdGroup"
  val clusterId = "clusterId"
  val clusterIdGroup = "clusterIdGroup"
  val srcClusterId = "srcClusterId"
  val srcClusterIdGroup = "srcClusterIdGroup"
  val dstClusterId = "dstClusterId"
  val dstClusterIdGroup = "dstClusterIdGroup"
  val noTransactions = "noTransactions"
  val estimatedValue = "estimatedValue"
  val fiatValues = "fiatValues"
  val category = "category"
  val abuse = "abuse"
}
