name: sbt test

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      JAVA_OPTS: -Xmx4G
    strategy:
      matrix:
        java:
          - 8
    
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Test with SBT
      run: |
        sbt test
